### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by farhanlatheef** [situmtech/situm-android-getting-started#18]
I updated few dependencies, now i am getting following error.

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
        at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
        at es.situm.sdk.location.a.d.b.a.a(Unknown Source)
        at es.situm.sdk.location.SitumLocationService$1.onReceive(Unknown Source)
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311)
        at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47)
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

my current dependency.

```
ext {
    supportLibraryVersion = '27.1.1'
    playServicesVersion = '15.0.1'
    jacksonVersion = '2.7.2'
    butterknifeVersion = '8.8.1'
    firebaseVersion = '17.1.0'
}

dependencies {
    ...
    implementation "com.android.support:appcompat-v7:$supportLibraryVersion"
    implementation "com.android.support:cardview-v7:$supportLibraryVersion" // indirect
    implementation "com.android.support:gridlayout-v7:$supportLibraryVersion" // indirect
    implementation "com.android.support:support-v13:$supportLibraryVersion" // indirect
    implementation "com.android.support:recyclerview-v7:$supportLibraryVersion"
    implementation "com.android.support:design:$supportLibraryVersion"

    implementation "com.google.android.gms:play-services-maps:$playServicesVersion"
    implementation "com.google.firebase:firebase-messaging:$firebaseVersion"
    
    implementation('es.situm:situm-sdk:2.24.0@aar') {
        transitive = true
    }

    ...
}
```

**Comment by CrisBarreiro** [comment]
We are closing issues in order to unify our support channels. In the problem persists, please drop an email to support@situm.es and we will be happy to help you
